name: Python Linting

on:
  pull_request:
    paths:
      - 'client/python/**'
      - '.github/workflows/**' # Re-run if a workflow is modified - useful to test workflow changes in PRs
  push:
    branches: [main]

jobs:
  pre_commit_checks:
    name: pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: check backend
        uses: pre-commit/action@v3.0.0
